name: octo_development
host: '127.0.0.1'
port: 9042
keyspace: octo_development
max_retries: 3
retry_delay: 0.5
replication:
  class: SimpleStrategy
  replication_factor: 1
redis:
  host: 127.0.0.1
  port: 6379
statsd:
  host: 127.0.0.1
  port: 8125
kafka:
  brokers:
    - 127.0.0.1:9092
  client_id: octomatic_development
  topic: events
kong:
  ratelimiting:
    day: 100000
    minute: 100
    second: 100
    hour: 10000
    month: 100000
    year: 1000000000
dashboard:
  title: 'Octo Dashboard'
aws:
  region: 'ap-southeast-1'
  secret_key: 'S6wzZDwQDoWAF7U+mbuFHR5uUhzp8ybxiJJjB8Yg'
  access_key: 'AKIAJSPC6N3YAZRKVJTA'
  bucket_name: 'octo-enterprise'